services:
  mariamaven-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mariamaven-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariamaven-db:3306/mariamaven
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - springnet

  mariamaven-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mariamaven
    ports:
      - "3306:3306"
    networks:
      - springnet

networks:
  springnet:
